"""1

Revision ID: baa8097ba809
Revises: 
Create Date: 2022-05-25 09:04:28.756655

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'baa8097ba809'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_extradition', sa.Date(), nullable=False),
    sa.Column('government', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('files', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_material_all',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name_production', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('quantity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider__company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('control_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signature_id', sa.Integer(), nullable=False),
    sa.Column('transport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_packaging', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=False),
    sa.Column('sampling_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sampling_date', sa.Date(), nullable=False),
    sa.Column('quality_opinion_person', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_attorney',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power_attorney', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_extradition', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('files', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['power_attorney.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('date_signature', sa.Date(), nullable=False),
    sa.Column('power_attorney_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['power_attorney_id'], ['power_attorney.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_work', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_begin', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('signature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signature_id'], ['signature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_general_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name_project', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('developer__company_id', sa.Integer(), nullable=False),
    sa.Column('customer__company_id', sa.Integer(), nullable=False),
    sa.Column('building_permit__company_id', sa.Integer(), nullable=False),
    sa.Column('planner__company_id', sa.Integer(), nullable=False),
    sa.Column('expertise__document_id', sa.Integer(), nullable=False),
    sa.Column('developer_person__company_id', sa.Integer(), nullable=False),
    sa.Column('representative_builder__company_id', sa.Integer(), nullable=False),
    sa.Column('representative_builder_or_customer__company_id', sa.Integer(), nullable=False),
    sa.Column('representative_builder_control__company_id', sa.Integer(), nullable=False),
    sa.Column('representative_other__company_id', sa.Integer(), nullable=False),
    sa.Column('building_supervision__company_id', sa.Integer(), nullable=False),
    sa.Column('capital_construction_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capital_construction_short_characteristics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capital_construction_date_begin', sa.Date(), nullable=False),
    sa.Column('capital_construction_date_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['expertise__document_id'], ['certificate.id'], ),
    sa.ForeignKeyConstraint(['id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_general_work')
    op.drop_table('journal')
    op.drop_table('signature')
    op.drop_table('power_attorney')
    op.drop_table('journal_material_all')
    op.drop_table('certificate')
    # ### end Alembic commands ###