"""20220620174500

Revision ID: 4a34b4aeb8ca
Revises: b80f3fa3ee16
Create Date: 2022-06-20 17:44:25.215511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a34b4aeb8ca'
down_revision = 'b80f3fa3ee16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###