"""20220621144000

Revision ID: 4e3e960a2f64
Revises: add743762aca
Create Date: 2022-06-21 14:40:34.337263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3e960a2f64'
down_revision = 'add743762aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###