"""20220621140500

Revision ID: add743762aca
Revises: c0423c8337da
Create Date: 2022-06-21 14:06:02.805984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add743762aca'
down_revision = 'c0423c8337da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###