"""20220621135000

Revision ID: c0423c8337da
Revises: 4a34b4aeb8ca
Create Date: 2022-06-21 13:50:19.010025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0423c8337da'
down_revision = '4a34b4aeb8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_bolted_mounting_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developed_project_documentation__contragent_id', sa.Integer(), nullable=True, comment='Организация, разработавшая проектную документацию, чертежи КМ'),
    sa.Column('developed_project_documentation_cipher_project', sa.String(), nullable=True, comment='Шифр проекта'),
    sa.Column('bolt_diameters_and_strength_classes', sa.String(), nullable=True, comment='Диаметры и классы прочности болтов'),
    sa.Column('developed_project_for_the_production_of_works__contragent_id', sa.Integer(), nullable=True, comment='Организация, разработавшая проект производства работ'),
    sa.Column('developed_project_for_the_production_of_works_cipher_project', sa.String(), nullable=True, comment='Шифр проекта'),
    sa.Column('developed_manufactured_structures__contragent_id', sa.Integer(), nullable=True, comment='Предприятие, разработавшее чертежи КМД и изготовившее конструкции'),
    sa.Column('developed_manufactured_structures_cipher_order', sa.String(), nullable=True, comment='Шифр заказа'),
    sa.Column('customer__contragent_id', sa.Integer(), nullable=True, comment='Заказчик (организация)'),
    sa.Column('customer__signature_id', sa.Integer(), nullable=True, comment='Подпись заказчика руководителя (представителя) технического надзора'),
    sa.ForeignKeyConstraint(['id'], ['journal_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_bolted_mounting_connections')
    # ### end Alembic commands ###